### ISSUE TITLE
[EPIC] Redesign My Reqeusts screen 22

### ISSUE THREAD

**Issue by baali** [HelpinOutMovement/helpinout-app-android#32]
This would be epic comprising of following tasks:

- [ ] Add `view details` to my requests item.
- [ ] Show payment preference in details of the item selected for `view details`. 
- [ ] Option of `Cancel this request` to be shown in details of request on this screen.
- [ ] Create New Request action with `+` icon on the top. It should show option of `Myself` or `Someone Else` on being clicked and take user to Home Screen as clarified by @hellomitesh in comment below.
- [ ] Show 3 item card content around the request:
   - [ ] Offers Received. Number of offers shown in `RED` color if there are new offers. Otherwise show count in DARK-GREY color. Clicking on this option takes user to Screen 23.
   - [ ] Requests sent. Count of how many requests were sent out. Clicking on it takes user to Screen 22b.
   - [ ] Search for Help Givers, New Matches, that takes users to Screen 17. Text in red when there are new offers available in the vicinity.

![Screenshot from 2020-05-01 18-53-56](https://user-images.githubusercontent.com/451188/80808444-39160880-8bdd-11ea-9ec1-af95387d21e4.png)

**Comment by hellomitesh** [comment]
+ (Add new request goes to Home Page because we need to know the location of the request.

**Comment by AvneeshGupta1** [comment]
fixed
