### ISSUE TITLE
[EPIC] redesign Requests Sent, Screen 22b

### ISSUE THREAD

**Issue by baali** [HelpinOutMovement/helpinout-app-android#33]
- [ ] This screen would be accessible from screen 22, when user clicks on "Requests sent" row of the card showing details of the Request.
- [ ] Only show First letter and last name of the user in details.
- [ ] Move `Rate` below the name of person offering help.
- [ ] Just like screen 22, it has `view details` that shows details of the request in pop up.
- [ ] We now will have `Report/Block` instead of `Rate/Report` at bottom of the request.
- [ ] “Not yet rated” text in place of stars if there is no rating done for the person offering help.
- [ ] Call them, break the text.

![Screenshot from 2020-05-01 19-29-19](https://user-images.githubusercontent.com/451188/80810784-2baf4d00-8be2-11ea-9e63-9637e2c02f23.png)

**Comment by AvneeshGupta1** [comment]
fixed
