### ISSUE TITLE
[EPIC] redesign My Offers, Screen 24

### ISSUE THREAD

**Issue by baali** [HelpinOutMovement/helpinout-app-android#34]
- [ ] A `+` Icon :heavy_plus_sign: on Header to create a new Offer and takes user to Screen 10.
- [ ] A `Mail` Icon :email: on Header that gives user an option to receive all requests received data in EMail.
- [ ] View details button on every offer. When clicked, show popup at bottom with:
   - [ ] Details of the offer.
   - [ ] Cancel the offer button.
- [ ] Card content in 3 rows.
   - [ ] First row: `Requests Received`. Shows numbers of requests received. If there are new, unread requests, number is shown in RED color otherwise DARK-GREY color.
   - [ ] Second row: `Offers Sent` and count. Takes user to Screen 24b 
   - [ ] Third row: Search for Help Seekers. If there are new matches for the Offer, show `New Matches` text in RED color.Takes user to Screen 18. 
- [ ] Remove Screen 24a.

![Screenshot from 2020-05-01 23-22-50](https://user-images.githubusercontent.com/451188/80828411-dc2d4900-8c02-11ea-8c86-f05140c0bddc.png)

**Comment by AvneeshGupta1** [comment]
fixed
