### ISSUE TITLE
[EPIC] Redisgn Offers sent Screen 24b

### ISSUE THREAD

**Issue by baali** [HelpinOutMovement/helpinout-app-android#35]
- [ ] All names to be First letter of first name and Last name.
- [ ] Show Ratings(in stars if available) below name. `Not rated yet` when user doesn't have existing ratings. 
- [ ] View details button for Offers, when clicked pops up at bottom:
  - [ ] Shows Offer sent details.
  - [ ] Shows status around Payments, Can/Cannot pay.
- [ ] Remove `Cancel this Request` option at the bottom of sent offers. 
- [ ] Add Report/Block options below `View details`. 
- [ ] Delete option on right side of Report/Block.

![24b](https://user-images.githubusercontent.com/451188/80829400-ac7f4080-8c04-11ea-8be9-003bba118098.png)

**Comment by AvneeshGupta1** [comment]
its was requirement changed. now if already rated then no rate button should be there and on click on stars it should be open other wise rate button should be displayed.
