### ISSUE TITLE
[EPIC] Redisgn Requests received from Screen 25

### ISSUE THREAD

**Issue by baali** [HelpinOutMovement/helpinout-app-android#36]
- [ ] All names to be First letter of first name and Last name.
- [ ] Show Ratings(in stars if available) below name. Not rated yet when user doesn't have existing ratings.
- [ ] View details button for Offers, when clicked pops up at bottom:
  - [ ] Shows Offer sent details.
  - [ ] Shows status around Payments, Can/Cannot pay.
- [ ] Break `Call them` in two lines. RED color. Below the Phone :telephone_receiver: icon.
![Screenshot from 2020-05-01 23-35-23](https://user-images.githubusercontent.com/451188/80829746-58c12700-8c05-11ea-9036-7a31e10fa7ef.png)

**Comment by AvneeshGupta1** [comment]
fixed
